parameters:
    beryllium_cache.class: Beryllium\CacheBundle\Cache
    beryllium_cache.client.class: Beryllium\CacheBundle\Client\MemcacheClient
    beryllium_cache.client.memcache.class: Memcache
    beryllium_cache.client.servers: { 127.0.0.1 : 11211 }
    beryllium_cache.client.prefix: ''
    beryllium_cache.default_ttl: 300

services:
    beryllium_cache.client.memcache:
      class: %beryllium_cache.client.memcache.class%
    beryllium_cache.client:
      class: %beryllium_cache.client.class%
      arguments: [@beryllium_cache.client.memcache]
      calls:
        - [ addServers, [ %beryllium_cache.client.servers% ] ]
        - [ setPrefix, [ %beryllium_cache.client.prefix% ] ]
    beryllium_cache:
        class: %beryllium_cache.class%
        calls:
          - [ setContainer, [ @service_container ] ]
          - [ setClient, [ @beryllium_cache.client ] ]
          - [ setTtl, [ %beryllium_cache.default_ttl% ] ]
